apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: product-catalog-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: product-catalog-service
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Pods
    pods:
      metric:
        name: requests_per_second # Nama metrik kustom dari Prometheus Adapter
      target:
        type: AverageValue
        averageValue: 100m # Target nilai rata-rata metrik, misalnya 100 milrequests/detik