apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: e-commerce-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: [region].ecommerce.com
      http:
      paths:
        - path: /product-catalog
          pathType: Prefix
          backend:
            service:
              name: product-catalog-service
              port:
                number: 80
    - path: /payment
      pathType: Prefix
      backend:
        service:
          name: payment-service
          port:
            number: 80
